SUPABASE_URL = "https://jlsuxnurkxgzvuonqbxh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsc3V4bnVya3hnenZ1b25xYnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0ODAwMTUsImV4cCI6MjA3NzA1NjAxNX0.yAqmHp_rQO6D1788O2IKedbWiDOeBDVDk1ubXSyKplM"
GOOGLE_API_KEY = "AIzaSyAlcp0WxzDHtU-tG5dm7hHluywUhdsZYa4"
N8N_WEBHOOK_URL = "http://localhost:5678/webhook/webhook-enrollment"
